In [1]:
import numpy as np
from numpy import linalg as LA
from F_matrix import F_matrix

In [ ]:
def F_RANSAC(image_points_1, image_points_2, threshold, n_iters):
    # image_points_1  : N*3 matrix of a normalized 2D homogeneous of image 1 
    # image_points_2  : N*3 matrix of a normalized 2D homogeneous of image 2
    # threshold       : Inlier threshold
    # n_iters         : Number of Iterations 
    
    inliers = []
    
    for i in range(n_iters):
        indices = np.random.choice(image_points_1.shape[0], n, replace=False)  
        
    return F

In [2]:
a = np.arange(9)
print(np.reshape(a, (3,3)))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
