In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import time
import os
from decompose_essential_matrix import *

In [2]:
def correspondingFeatureDetection(img1, img2):

    orb = cv2.ORB_create()
    Keypoints1, Descriptors1 = orb.detectAndCompute(img1, None)
    Keypoints2, Descriptors2 = orb.detectAndCompute(img2, None)
    
    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)

    # Match descriptors.
    matches = bf.match(Descriptors1,Descriptors2)

    # Sort them in the order of their distance.
    matches = sorted(matches, key = lambda x:x.distance)
    kp1_list = np.mat([])
    kp2_list = np.mat([])
    k = 0

    number_of_matches = 150

    for m in matches:
        img1Idx = m.queryIdx
        img2Idx = m.trainIdx

        (img1x, img1y) = Keypoints1[img1Idx].pt
        (img2x, img2y) = Keypoints2[img2Idx].pt

        if k == 0:
            kp1_list = [[img1x,img1y,1]]
            kp2_list = [[img2x,img2y,1]]
            k = 1
        else:
            kp1_list = np.append(kp1_list,[[img1x,img1y,1]],axis = 0)
            kp2_list = np.append(kp2_list,[[img2x,img2y,1]],axis = 0)
            k+=1
        if k == number_of_matches:
            break
    return kp1_list,kp2_list

In [3]:
def F_matrix(image_coords_1, image_coords_2):
    '''
    image_coords_1  : N*3 homogeneous coordinates of image pixels    
    image_coords_2  : N*3 homogeneous coordinates of image pixels
    return          : Fundamental Matrix of dimension 3*3
    '''
    
    A = np.zeros((len(image_coords_1),9))

    # Constructing A matrix of size N*9
    for i in range(len(image_coords_1)):
        A[i,:] = np.kron(image_coords_1[i,:], image_coords_2[i,:])
        
    u, s, vh = np.linalg.svd(A, full_matrices=True)
    F = np.reshape(vh[8,:], (3,3))
    uf, sf, vhf = np.linalg.svd(F, full_matrices=True)
    
    F = uf @ np.diag(np.array([sf[0], sf[1], 0])) @ vhf

    return F

In [4]:
def F_RANSAC(image_points_1, image_points_2, threshold, n_iters):
    '''
        image_points_1  : N*3 matrix of a normalized 2D homogeneous of image 1 
        image_points_2  : N*3 matrix of a normalized 2D homogeneous of image 2
        threshold       : Inlier threshold
        n_iters         : Number of Iterations 
        return          : Fundamental Matrix of dimension 3*3
    '''

    n = 8 
    F = np.zeros((3,3))
    max_inliers = -9999999

    for i in range(n_iters):

        # Randomly sample 8 matching points from image 1 and image 2
        indices = np.random.choice(image_points_1.shape[0], n, replace=False)  
        matched_points_1 = image_points_1[indices] 
        matched_points_2 = image_points_2[indices]

        # Get the F matrix for the current iteration
        F_current = F_matrix(matched_points_1, matched_points_2)

        # Counting the number of inliers 
        number_current_inliers = 0
        for i in range(len(image_points_1)):
            error = np.abs(image_points_2[i,:] @ F_current @ image_points_1[i,:].T)
            if error < threshold:
                number_current_inliers += 1

        # Updating F matrix
        if number_current_inliers > max_inliers:
            max_inliers = number_current_inliers
            F = F_current
    return F

In [5]:
def NormalizationMat(image_coords):
    '''
        image_coords : N*3 matrix of image coordinates
        return       : 3*3 Scale Transformation matrix 
    '''

    mu = np.mean(image_coords,axis = 0)
    d = 0
    for i in range(len(image_coords)):
        d = d + np.sqrt((image_coords[i,0] - mu[0])**2 + (image_coords[i,1] - mu[1])**2)

    d = d/i
    T = np.mat([
        [1.44/d, 0, -1.44 * mu[0]/d], 
        [0, 1.44/d, -1.44 * mu[1]/d],
        [0,      0,               1]
        ])
    
    return T

In [7]:
if __name__ == "__main__":
    ground_truth = np.loadtxt('../mr19-assignment2-data/ground-truth.txt')
    ground_truth_translation = np.concatenate((np.concatenate((np.array([ground_truth[:,3]]).T, np.array([ground_truth[:,7]]).T), axis=1), np.array([ground_truth[:,11]]).T ), axis=1)
    for i in range(800, 0, -1):
        ground_truth_translation[i] = ground_truth_translation[i] - ground_truth_translation[i-1]
    ground_truth_norm = np.linalg.norm(ground_truth_translation, axis=1)

    C = np.concatenate((np.eye(3), np.zeros((3,1))), axis = 1) 
    C = np.concatenate((C, np.array([[0, 0, 0, 1]])), axis = 0)
    
    K  = np.array([[7.215377e+02, 0.000000e+00, 6.095593e+02],[0.000000e+00, 7.215377e+02, 1.728540e+02],[0.000000e+00, 0.000000e+00, 1.000000e+00]])
    
    f = open('results.txt','wb')
    K_inverse = np.linalg.inv(K)

    cumulative_translation = np.zeros((3,1))
    cumulative_orientation = np.eye(3)
    initial_matrix = np.concatenate((cumulative_translation, cumulative_orientation), axis=1)
    np.savetxt(f,np.reshape(initial_matrix, (1,12)))

    dirFiles = os.listdir('../mr19-assignment2-data/images/')
    for i in range(len(dirFiles)):
        dirFiles[i] = dirFiles[i].split(".")[0]

    dirFiles.sort(key=float)
    for i in range(len(dirFiles)):
        dirFiles[i] = '../mr19-assignment2-data/images/' + dirFiles[i] + '.png'

    key_point_1 = np.zeros((800,150,3))
    key_point_2 = np.zeros((800,150,3))

    for i in range(1,len(dirFiles)):
        print("Iteration {}".format(i))
        img1 = cv2.imread(dirFiles[i-1])
        img2 = cv2.imread(dirFiles[i])

        kp1, kp2 = correspondingFeatureDetection(img1, img2)
        key_point_1[i-1] = kp1
        key_point_2[i-1] = kp2



    for i in range(1, len(dirFiles)):
        print("Iteration {}".format(i))


        kp1 = key_point_1[i-1]
        kp2 = key_point_2[i-1]
        if i > 1:
            kpPrev = key_point_2[i - 2]

        T1 = NormalizationMat(kp1)
        T2 = NormalizationMat(kp2)

        points1 = T1 @ kp1.T
        points2 = T2 @ kp2.T

        F = F_RANSAC(points1.T, points2.T, 0.005, 300)
        FundamentalMatrix = T2.T @ F @ T1
        E = compute_essential_matrix(FundamentalMatrix, K)
        
        
        Transformation_info = cv2.recoverPose(E, (kp1[:,0:2]), (kp2[:,0:2]), K)
        Rotation = Transformation_info[1].T
        Translation = -Transformation_info[2]
        Translation = Translation / np.linalg.norm(Translation) * ground_truth_norm[i]
        print("Translation: ",Translation)

        Transformation = np.concatenate((Rotation, Translation), axis = 1)
        Transformation = np.concatenate((Transformation, np.array([[0, 0, 0, 1]])), axis = 0)
        C = C @ Transformation

        print("C : ", C)
        Reshaped = np.reshape(C[0:3,:],(1,12))
        np.savetxt(f, Reshaped)

800 - 799
799 - 798
798 - 797
797 - 796
796 - 795
795 - 794
794 - 793
793 - 792
792 - 791
791 - 790
790 - 789
789 - 788
788 - 787
787 - 786
786 - 785
785 - 784
784 - 783
783 - 782
782 - 781
781 - 780
780 - 779
779 - 778
778 - 777
777 - 776
776 - 775
775 - 774
774 - 773
773 - 772
772 - 771
771 - 770
770 - 769
769 - 768
768 - 767
767 - 766
766 - 765
765 - 764
764 - 763
763 - 762
762 - 761
761 - 760
760 - 759
759 - 758
758 - 757
757 - 756
756 - 755
755 - 754
754 - 753
753 - 752
752 - 751
751 - 750
750 - 749
749 - 748
748 - 747
747 - 746
746 - 745
745 - 744
744 - 743
743 - 742
742 - 741
741 - 740
740 - 739
739 - 738
738 - 737
737 - 736
736 - 735
735 - 734
734 - 733
733 - 732
732 - 731
731 - 730
730 - 729
729 - 728
728 - 727
727 - 726
726 - 725
725 - 724
724 - 723
723 - 722
722 - 721
721 - 720
720 - 719
719 - 718
718 - 717
717 - 716
716 - 715
715 - 714
714 - 713
713 - 712
712 - 711
711 - 710
710 - 709
709 - 708
708 - 707
707 - 706
706 - 705
705 - 704
704 - 703
703 - 702
702 - 701
701 - 700


Iteration 36
Iteration 37
Iteration 38
Iteration 39
Iteration 40
Iteration 41
Iteration 42
Iteration 43
Iteration 44
Iteration 45
Iteration 46
Iteration 47
Iteration 48
Iteration 49
Iteration 50
Iteration 51
Iteration 52
Iteration 53
Iteration 54
Iteration 55
Iteration 56
Iteration 57
Iteration 58
Iteration 59
Iteration 60
Iteration 61
Iteration 62
Iteration 63
Iteration 64
Iteration 65
Iteration 66
Iteration 67
Iteration 68
Iteration 69
Iteration 70
Iteration 71
Iteration 72
Iteration 73
Iteration 74
Iteration 75
Iteration 76
Iteration 77
Iteration 78
Iteration 79
Iteration 80
Iteration 81
Iteration 82
Iteration 83
Iteration 84
Iteration 85
Iteration 86
Iteration 87
Iteration 88
Iteration 89
Iteration 90
Iteration 91
Iteration 92
Iteration 93
Iteration 94
Iteration 95
Iteration 96
Iteration 97
Iteration 98
Iteration 99
Iteration 100
Iteration 101
Iteration 102
Iteration 103
Iteration 104
Iteration 105
Iteration 106
Iteration 107
Iteration 108
Iteration 109
Iteration 110
Iteration 111


Iteration 631
Iteration 632
Iteration 633
Iteration 634
Iteration 635
Iteration 636
Iteration 637
Iteration 638
Iteration 639
Iteration 640
Iteration 641
Iteration 642
Iteration 643
Iteration 644
Iteration 645
Iteration 646
Iteration 647
Iteration 648
Iteration 649
Iteration 650
Iteration 651
Iteration 652
Iteration 653
Iteration 654
Iteration 655
Iteration 656
Iteration 657
Iteration 658
Iteration 659
Iteration 660
Iteration 661
Iteration 662
Iteration 663
Iteration 664
Iteration 665
Iteration 666
Iteration 667
Iteration 668
Iteration 669
Iteration 670
Iteration 671
Iteration 672
Iteration 673
Iteration 674
Iteration 675
Iteration 676
Iteration 677
Iteration 678
Iteration 679
Iteration 680
Iteration 681
Iteration 682
Iteration 683
Iteration 684
Iteration 685
Iteration 686
Iteration 687
Iteration 688
Iteration 689
Iteration 690
Iteration 691
Iteration 692
Iteration 693
Iteration 694
Iteration 695
Iteration 696
Iteration 697
Iteration 698
Iteration 699
Iteration 700
Iteration 701
Iterat

Translation:  [[0.27726277]
 [0.05130993]
 [0.8462054 ]]
C :  [[ 9.91272945e-01  1.15545504e-01 -6.34601037e-02  1.19338369e-01]
 [-1.15177288e-01  9.93300070e-01  9.44259939e-03  1.26562663e-02]
 [ 6.41259753e-02 -2.05103069e-03  9.97939704e-01  1.74630229e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 20
Translation:  [[-0.11251689]
 [-0.01886941]
 [ 0.88488307]]
C :  [[ 9.91549338e-01  1.15712195e-01 -5.86566106e-02 -5.05316220e-02]
 [-1.15284294e-01  9.93275566e-01  1.06387046e-02  1.52282672e-02]
 [ 5.94932059e-02 -3.78661458e-03  9.98221529e-01  1.83389063e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 21
Translation:  [[-0.08932962]
 [-0.01279124]
 [ 0.88304173]]
C :  [[ 9.91905322e-01  1.13920509e-01 -5.60887638e-02 -1.92382688e-01]
 [-1.13504437e-01  9.93481378e-01  1.05591253e-02  2.22157686e-02]
 [ 5.69260432e-02 -4.10732898e-03  9.98369949e-01  1.92151115e+01]
 [ 0.00000000e+00  0.00000000e+00  0.000000

Translation:  [[-0.17910139]
 [ 0.011337  ]
 [ 0.65279691]]
C :  [[ 9.90624165e-01 -2.58201965e-02 -1.34153202e-01 -1.87050692e+00]
 [ 3.20511864e-02  9.98495263e-01  4.44964099e-02  3.12077390e-01]
 [ 1.32802431e-01 -4.83789881e-02  9.89961104e-01  3.51867943e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 45
Translation:  [[-0.17630057]
 [ 0.01250437]
 [ 0.63915948]]
C :  [[ 9.92502586e-01  6.58666989e-03 -1.22046026e-01 -2.13122268e+00]
 [-2.74889505e-03  9.99497225e-01  3.15870410e-02  3.47352601e-01]
 [ 1.22192718e-01 -3.10147282e-02  9.92021686e-01  3.57955192e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 46
Translation:  [[-7.29405925e-02]
 [-7.28983439e-05]
 [ 6.49031065e-01]]
C :  [[ 9.92954742e-01  2.16451087e-03 -1.18474450e-01 -2.28282855e+00]
 [ 1.09288820e-03  9.99623331e-01  2.74226558e-02  3.67981216e-01]
 [ 1.18489181e-01 -2.73589355e-02  9.92578361e-01  3.64304615e+01]
 [ 0.00000000e+00  0.0000000

Translation:  [[ 0.10186263]
 [ 0.00467963]
 [-0.24093815]]
C :  [[ 9.99206404e-01 -1.37259481e-02 -3.73919978e-02 -2.42101597e+00]
 [ 1.35133524e-02  9.99891092e-01 -5.93241864e-03  3.82180026e-01]
 [ 3.74693536e-02  5.42241945e-03  9.99283065e-01  4.13372094e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 69
Translation:  [[-0.09532413]
 [-0.01424887]
 [ 0.24130513]]
C :  [[ 9.99740519e-01 -8.80683679e-03 -2.10079558e-02 -2.52509174e+00]
 [ 8.61525209e-03  9.99920632e-01 -9.19276591e-03  3.65213036e-01]
 [ 2.10872477e-02  9.00939172e-03  9.99737045e-01  4.15746926e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 70
Translation:  [[-0.10440834]
 [-0.01050013]
 [ 0.23577065]]
C :  [[ 9.99999161e-01  9.85785707e-04  8.40441780e-04 -2.63433358e+00]
 [-9.74398110e-04  9.99909151e-01 -1.34439498e-02  3.51646856e-01]
 [-8.53618280e-04  1.34431196e-02  9.99909273e-01  4.18081049e+01]
 [ 0.00000000e+00  0.00000000e+00  0.000

Translation:  [[0.11310245]
 [0.0126771 ]
 [0.38287192]]
C :  [[ 0.77369496 -0.06754123  0.62994784 -0.71497546]
 [ 0.12801184  0.99045901 -0.0510285   0.46544126]
 [-0.62049099  0.12012128  0.77495923 42.74780333]
 [ 0.          0.          0.          1.        ]]
Iteration 94
Translation:  [[-0.10693141]
 [-0.0045092 ]
 [ 0.39567374]]
C :  [[ 0.73327865 -0.06381116  0.67692729 -0.54814938]
 [ 0.12658458  0.99099252 -0.04370541  0.42709595]
 [-0.66804099  0.11773679  0.73475117 43.12024267]
 [ 0.          0.          0.          1.        ]]
Iteration 95
Translation:  [[-0.03033844]
 [-0.00140782]
 [ 0.4268883 ]]
C :  [[ 6.91969290e-01 -6.97398370e-02  7.18550525e-01 -2.81333746e-01]
 [ 1.35552401e-01  9.90171570e-01 -3.44355666e-02  4.03203111e-01]
 [-7.09086770e-01  1.21229603e-01  6.94621721e-01  4.34540009e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 96
Translation:  [[-0.04970181]
 [ 0.01302851]
 [ 0.43639887]]
C :  [[ 6.47887513e-01 -6.7512

Translation:  [[-0.13027127]
 [ 0.03731359]
 [ 0.69086507]]
C :  [[ 0.1660179  -0.16998644  0.97136124 10.10414398]
 [ 0.15344712  0.97748537  0.1448321   1.02731698]
 [-0.9741109   0.12500786  0.18836399 45.250522  ]
 [ 0.          0.          0.          1.        ]]
Iteration 121
Translation:  [[ 0.32149307]
 [-0.10090445]
 [ 0.63837714]]
C :  [[ 0.17447877 -0.17030324  0.96982162 10.79476479]
 [ 0.15990783  0.9767555   0.14275213  1.07047404]
 [-0.97158975  0.13017486  0.19765592 45.04498552]
 [ 0.          0.          0.          1.        ]]
Iteration 122
Translation:  [[-0.44721098]
 [ 0.00169788]
 [ 0.58828459]]
C :  [[ 0.1664871  -0.17083413  0.9711322  11.28697792]
 [ 0.15738955  0.97685441  0.1448585   1.08459879]
 [-0.97340155  0.12872899  0.18952117 45.59599007]
 [ 0.          0.          0.          1.        ]]
Iteration 123
Translation:  [[ 0.18546798]
 [-0.06176047]
 [ 0.71274725]]
C :  [[ 0.17207301 -0.18053529  0.96839965 12.02057855]
 [ 0.1418581   0.97735749  0.156

Translation:  [[-0.02827776]
 [-0.02718528]
 [ 0.75476766]]
C :  [[ 0.27663211 -0.19438385  0.94111083 27.55127845]
 [-0.05027027  0.97506017  0.21617254  3.98841258]
 [-0.95966014 -0.10711016  0.25996122 49.39063337]
 [ 0.          0.          0.          1.        ]]
Iteration 147
Translation:  [[-0.10838988]
 [-0.07216603]
 [ 0.74557424]]
C :  [[ 0.27545838 -0.19489732  0.94134888 28.23699023]
 [-0.05070464  0.97492372  0.21668591  4.08466782]
 [-0.95997485 -0.1074187   0.25866871 49.69620092]
 [ 0.          0.          0.          1.        ]]
Iteration 148
Translation:  [[-0.11736762]
 [-0.05637922]
 [ 0.7530044 ]]
C :  [[ 0.27665515 -0.18893933  0.94221222 28.92448834]
 [-0.06933673  0.97400088  0.21567268  4.1988189 ]
 [-0.95846458 -0.12499687  0.25636192 50.00970574]
 [ 0.          0.          0.          1.        ]]
Iteration 149
Translation:  [[-0.03895979]
 [-0.05670249]
 [ 0.76469121]]
C :  [[ 0.28029594 -0.18797654  0.94132832 29.64492465]
 [-0.07179212  0.97378689  0.215

Translation:  [[-0.11863025]
 [-0.01086311]
 [ 0.74746847]]
C :  [[ 0.53130995 -0.26422136  0.80492038 42.30240663]
 [-0.16904367  0.89794856  0.40634053  9.96978316]
 [-0.83014094 -0.35195947  0.43242405 57.25643039]
 [ 0.          0.          0.          1.        ]]
Iteration 175
Translation:  [[-0.12585702]
 [ 0.0084092 ]
 [ 0.72940498]]
C :  [[ 0.53235592 -0.25716031  0.80651457 42.82042858]
 [-0.17562936  0.89845712  0.40240418 10.29499633]
 [-0.82810114 -0.35586989  0.43313407 57.67336201]
 [ 0.          0.          0.          1.        ]]
Iteration 176
Translation:  [[-0.12443427]
 [-0.05423748]
 [ 0.71734645]]
C :  [[ 0.53243203 -0.25662195  0.80663579 43.34668335]
 [-0.17647631  0.89834497  0.40228401 10.55678381]
 [-0.82787212 -0.35654101  0.43301994 58.10641485]
 [ 0.          0.          0.          1.        ]]
Iteration 177
Translation:  [[-0.11841211]
 [-0.02904791]
 [ 0.70888104]]
C :  [[ 0.53415936 -0.2490093   0.80787879 43.86290011]
 [-0.18333083  0.89877337  0.398

Translation:  [[ 0.177081  ]
 [ 0.02050357]
 [-0.53203286]]
C :  [[ 0.50299627 -0.19295238  0.84247501 52.68581502]
 [-0.27002939  0.89088162  0.36525891 15.2406075 ]
 [-0.82102307 -0.41121687  0.39600732 65.75718651]
 [ 0.          0.          0.          1.        ]]
Iteration 204
Translation:  [[-0.11966874]
 [-0.01205325]
 [ 0.56032201]]
C :  [[ 0.50683763 -0.1912584   0.84055686 53.10000508]
 [-0.27092345  0.89032871  0.36594437 15.46684617]
 [-0.81836184 -0.41320094  0.39943571 66.08228543]
 [ 0.          0.          0.          1.        ]]
Iteration 205
Translation:  [[ 0.22550256]
 [ 0.02677917]
 [-0.54770354]]
C :  [[ 0.51891631 -0.17251171  0.83723687 52.74880056]
 [-0.28630627  0.88778174  0.36037799 15.22916547]
 [-0.80545303 -0.42671219  0.41129323 65.66790521]
 [ 0.          0.          0.          1.        ]]
Iteration 206
Translation:  [[-0.1204156 ]
 [ 0.00125091]
 [ 0.56419384]]
C :  [[ 0.52432619 -0.17637901  0.83305011 53.15846302]
 [-0.28070063  0.88782693  0.364

Translation:  [[-0.00481348]
 [-0.04654187]
 [ 0.72344285]]
C :  [[ 0.67523809 -0.25150714  0.69339576 66.68376308]
 [-0.09955357  0.90039267  0.42353526 22.08346161]
 [-0.7308506  -0.35501717  0.582941   76.58086917]
 [ 0.          0.          0.          1.        ]]
Iteration 233
Translation:  [[-0.13237727]
 [ 0.01603798]
 [ 0.72452006]]
C :  [[ 0.67298182 -0.26995535  0.68863603 67.09272237]
 [-0.07928253  0.89932692  0.4300295  22.41794051]
 [-0.73539768 -0.34399884  0.58382793 77.09427587]
 [ 0.          0.          0.          1.        ]]
Iteration 234
Translation:  [[ 0.01369376]
 [-0.06138317]
 [ 0.73513341]]
C :  [[ 0.67662694 -0.27224465  0.68414826 67.62474809]
 [-0.07844116  0.89719947  0.43460339 22.67778035]
 [-0.7321359  -0.34772974  0.58571414 77.53451266]
 [ 0.          0.          0.          1.        ]]
Iteration 235
Translation:  [[ 0.01412167]
 [-0.03714415]
 [ 0.70415137]]
C :  [[ 6.78075312e-01 -2.78783991e-01  6.80068642e-01  6.81261594e+01]
 [-7.16656083e-0

Translation:  [[-0.00548429]
 [-0.00615783]
 [ 0.5781997 ]]
C :  [[ 7.38677116e-01 -2.74976544e-01  6.15421822e-01  7.73915340e+01]
 [-1.88124668e-02  9.04242526e-01  4.26604671e-01  2.83096398e+01]
 [-6.73796861e-01 -3.26700711e-01  6.62770274e-01  8.61683332e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 258
Translation:  [[ 0.09871408]
 [-0.0249839 ]
 [ 0.57978715]]
C :  [[ 7.45334575e-01 -2.75417260e-01  6.07142243e-01  7.78281355e+01]
 [-1.59132893e-02  9.03071767e-01  4.29194771e-01  2.85325312e+01]
 [-6.66500666e-01 -3.29555332e-01  6.68707817e-01  8.64942479e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 259
Translation:  [[ 0.06885833]
 [-0.04238415]
 [ 0.59735104]]
C :  [[ 7.50898052e-01 -2.79341313e-01  5.98431740e-01  7.82538083e+01]
 [-1.12824710e-02  9.00582406e-01  4.34538878e-01  2.87495394e+01]
 [-6.60321756e-01 -3.33046186e-01  6.73093914e-01  8.68617750e+01]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[ 0.08029308]
 [-0.04235782]
 [ 0.84626124]]
C :  [[ 8.85494487e-01 -2.69218854e-01  3.78709285e-01  8.73089754e+01]
 [ 7.40421571e-02  8.86383535e-01  4.56992328e-01  3.47528886e+01]
 [-4.58712626e-01 -3.76623735e-01  8.04821278e-01  9.68558648e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 282
Translation:  [[ 0.03859553]
 [-0.01034938]
 [ 0.86524008]]
C :  [[ 8.91753883e-01 -2.50816051e-01  3.76651458e-01  8.76736123e+01]
 [ 5.61432980e-02  8.87232593e-01  4.57893280e-01  3.51419808e+01]
 [-4.49024434e-01 -3.87181655e-01  8.05274750e-01  9.75384219e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 283
Translation:  [[0.04238689]
 [0.00971937]
 [0.8636094 ]]
C :  [[ 8.93808226e-01 -2.46802730e-01  3.74426586e-01  8.80342529e+01]
 [ 5.52622682e-02  8.89189605e-01  4.54189309e-01  3.55484248e+01]
 [-4.45031389e-01 -3.85266478e-01  8.08403862e-01  9.82110689e+01]
 [ 0.00000000e+00  0.00000000e+00  0.0000

Translation:  [[ 0.13617864]
 [-0.08597796]
 [ 0.95294292]]
C :  [[  0.96041549  -0.22326126   0.16660284  97.48400318]
 [  0.12153397   0.87395576   0.47056437  44.9231292 ]
 [ -0.2506623   -0.43168941   0.86649447 114.38109325]
 [  0.           0.           0.           1.        ]]
Iteration 307
Translation:  [[ 0.03383513]
 [-0.06155653]
 [ 0.92150275]]
C :  [[ 9.63845079e-01 -2.03252707e-01  1.72310769e-01  9.76837671e+01]
 [ 1.00791735e-01  8.76707609e-01  4.70345399e-01  4.53070700e+01]
 [-2.46665138e-01 -4.35972597e-01  8.65496507e-01  1.15197662e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 308
Translation:  [[0.240433  ]
 [0.0077313 ]
 [0.90484532]]
C :  [[ 9.66355465e-01 -1.92908266e-01  1.70127940e-01  9.80698505e+01]
 [ 9.26328432e-02  8.78072145e-01  4.69476799e-01  4.57636716e+01]
 [-2.39950561e-01 -4.37922036e-01  8.66399457e-01  1.15918126e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 309
Transla

Translation:  [[-0.12608349]
 [-0.01930741]
 [ 0.90823743]]
C :  [[ 9.84095933e-01 -6.04767827e-02  1.67026209e-01  1.02887584e+02]
 [-2.97226671e-02  8.70948454e-01  4.90474620e-01  5.49999776e+01]
 [-1.75133545e-01 -4.87638543e-01  8.55299300e-01  1.33007367e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 332
Translation:  [[-0.12163196]
 [ 0.01707873]
 [ 0.92529848]]
C :  [[ 9.82752057e-01 -6.99988486e-02  1.71168209e-01  1.02921402e+02]
 [-2.52657093e-02  8.66090980e-01  4.99247493e-01  5.54723029e+01]
 [-1.83193991e-01 -4.94961187e-01  8.49384121e-01  1.33811747e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 333
Translation:  [[-0.12569189]
 [-0.03384039]
 [ 0.92273266]]
C :  [[ 9.79983351e-01 -8.06231584e-02  1.82023452e-01  1.02958190e+02]
 [-2.27634762e-02  8.62948836e-01  5.04778298e-01  5.59068417e+01]
 [-1.97773747e-01 -4.98817814e-01  8.43840230e-01  1.34635278e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[ 0.09108937]
 [-0.05586598]
 [ 0.80129279]]
C :  [[ 9.49997404e-01 -1.39886303e-01  2.79171550e-01  1.08612220e+02]
 [-2.14394249e-02  8.62711826e-01  5.05241187e-01  6.34145051e+01]
 [-3.11520920e-01 -4.85963093e-01  8.16574913e-01  1.49527677e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 356
Translation:  [[ 0.1594512 ]
 [-0.07045056]
 [ 0.77580167]]
C :  [[ 9.52431805e-01 -1.29979844e-01  2.75642697e-01  1.08990135e+02]
 [-2.75748031e-02  8.64016302e-01  5.02708127e-01  6.37422750e+01]
 [-3.03501707e-01 -4.86396002e-01  8.19332438e-01  1.50145741e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 357
Translation:  [[ 0.10716352]
 [-0.05125277]
 [ 0.77796576]]
C :  [[ 9.51601598e-01 -1.34691236e-01  2.76247478e-01  1.09313303e+02]
 [-2.12767447e-02  8.67821386e-01  4.96420530e-01  6.40861265e+01]
 [-3.06596964e-01 -4.78272217e-01  8.22954426e-01  1.50775559e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[-0.28930693]
 [-0.04655946]
 [ 0.62373805]]
C :  [[ 8.84684063e-01 -1.18868637e-01  4.50781939e-01  1.11934911e+02]
 [-1.37253213e-01  8.57677154e-01  4.95531487e-01  7.07730411e+01]
 [-4.45528523e-01 -5.00260078e-01  7.42458207e-01  1.64272954e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 380
Translation:  [[-0.31136965]
 [-0.04987473]
 [ 0.61628169]]
C :  [[ 8.76103427e-01 -1.19275850e-01  4.67136015e-01  1.11943184e+02]
 [-1.45527979e-01  8.58295998e-01  4.92086970e-01  7.10783881e+01]
 [-4.59635064e-01 -4.99100441e-01  7.34598092e-01  1.64894192e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 381
Translation:  [[-0.32955459]
 [-0.04539561]
 [ 0.61478747]]
C :  [[ 8.66465343e-01 -1.21893404e-01  4.84127884e-01  1.11947064e+02]
 [-1.52619103e-01  8.58636944e-01  4.89336293e-01  7.13899136e+01]
 [-4.75336953e-01 -4.97880102e-01  7.25375892e-01  1.65519945e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[0.1874028 ]
 [0.05891778]
 [0.87402242]]
C :  [[ 7.52974669e-01 -2.22187488e-02  6.57674292e-01  1.19901377e+02]
 [-3.17561152e-01  8.63083784e-01  3.92735657e-01  7.83813682e+01]
 [-5.76354112e-01 -5.04571808e-01  6.42824415e-01  1.76757660e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 404
Translation:  [[-0.08355082]
 [ 0.14684726]
 [-0.90247668]]
C :  [[ 7.46905289e-01 -3.90418338e-02  6.63783266e-01  1.19241667e+02]
 [-3.03746761e-01  8.67996238e-01  3.92836398e-01  7.81802074e+01]
 [-5.91498431e-01 -4.95033601e-01  6.36452150e-01  1.76151586e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 405
Translation:  [[ 0.0596645 ]
 [-0.10235788]
 [ 0.9100486 ]]
C :  [[ 7.44302818e-01 -3.56196564e-02  6.66891711e-01  1.19894302e+02]
 [-3.10375756e-01  8.65735473e-01  3.92643581e-01  7.84307385e+01]
 [-5.91337640e-01 -4.99232743e-01  6.33313875e-01  1.76746168e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000

Translation:  [[-0.03350464]
 [-0.06118675]
 [ 0.95916321]]
C :  [[ 6.97555217e-01 -5.37623247e-03  7.16510862e-01  1.31831627e+02]
 [-3.64094223e-01  8.58593914e-01  3.60904264e-01  8.44688561e+01]
 [-6.17132170e-01 -5.12628118e-01  5.96959209e-01  1.87202102e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 428
Translation:  [[ 0.57466009]
 [ 0.14013794]
 [-0.71228068]]
C :  [[ 6.96817143e-01 -9.47263439e-03  7.17186265e-01  1.31721374e+02]
 [-3.61808093e-01  8.58729931e-01  3.62874373e-01  8.41228821e+01]
 [-6.19306688e-01 -5.12340878e-01  5.94950461e-01  1.86350419e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 429
Translation:  [[-5.76687020e-04]
 [-1.00742709e-01]
 [ 9.31265527e-01]]
C :  [[ 6.95441390e-01 -9.74325575e-03  7.18516765e-01  1.32389818e+02]
 [-3.62223890e-01  8.58823813e-01  3.62236816e-01  8.43745124e+01]
 [-6.20608674e-01 -5.12178413e-01  5.93732386e-01  1.86956448e+02]
 [ 0.00000000e+00  0.00000

Translation:  [[-0.09059127]
 [-0.04046988]
 [ 0.88779523]]
C :  [[ 6.43195552e-01 -2.13563974e-02  7.65404067e-01  1.46966074e+02]
 [-3.76466176e-01  8.61627456e-01  3.40398803e-01  9.12633278e+01]
 [-6.66762852e-01 -5.07091738e-01  5.46154986e-01  1.99087892e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 452
Translation:  [[-0.40836262]
 [-0.07544673]
 [-0.78438123]]
C :  [[ 5.20025532e-01 -6.35803333e-02  8.51781068e-01  1.46104660e+02]
 [-2.98073917e-01  9.21025266e-01  2.50727738e-01  9.10850531e+01]
 [-8.00453238e-01 -3.84278545e-01  4.60005015e-01  1.98970038e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 453
Translation:  [[-0.02375451]
 [-0.00878012]
 [ 0.89963998]]
C :  [[ 5.16177449e-01 -6.41949519e-02  8.54072508e-01  1.46859161e+02]
 [-2.88331093e-01  9.25958301e-01  2.43857348e-01  9.13096117e+01]
 [-8.06489939e-01 -3.72129323e-01  4.59449393e-01  1.99406265e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[ 0.01818476]
 [-0.00086796]
 [ 0.85703107]]
C :  [[ 4.07183461e-01 -1.90944703e-02  9.13146774e-01  1.58223321e+02]
 [-4.05552048e-01  8.92036875e-01  1.99493732e-01  9.38741518e+01]
 [-8.18369822e-01 -4.51559093e-01  3.55478861e-01  2.05996768e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 476
Translation:  [[-0.61525293]
 [-0.00398238]
 [-0.59227027]]
C :  [[ 3.90570898e-01 -2.49098416e-02  9.20235770e-01  1.57432046e+02]
 [-4.17093228e-01  8.86355024e-01  2.01017441e-01  9.40019623e+01]
 [-8.20662911e-01 -4.62335670e-01  3.35794752e-01  2.06291532e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 477
Translation:  [[-0.32929836]
 [ 0.09372139]
 [-0.77626645]]
C :  [[ 3.79256956e-01 -2.57098774e-02  9.24934140e-01  1.56586749e+02]
 [-3.94597055e-01  8.99664605e-01  1.86806754e-01  9.40663377e+01]
 [-8.36933286e-01 -4.35824048e-01  3.31059017e-01  2.06257778e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[0.08932119]
 [0.03057472]
 [0.5963201 ]]
C :  [[ 5.66973194e-01 -2.51255544e-02  8.23352964e-01  1.64566730e+02]
 [-2.91235607e-01  9.28864415e-01  2.28894561e-01  9.56325128e+01]
 [-7.70534372e-01 -3.69566781e-01  5.19323768e-01  2.09801799e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 500
Translation:  [[0.06923248]
 [0.0310451 ]
 [0.56325389]]
C :  [[ 5.75549039e-01 -2.06450942e-02  8.17506626e-01  1.65068960e+02]
 [-2.89418965e-01  9.29837613e-01  2.27241451e-01  9.57701123e+01]
 [-7.64839831e-01 -3.67390520e-01  5.29192062e-01  2.10029491e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 501
Translation:  [[-0.17256433]
 [-0.10766136]
 [ 0.54264463]]
C :  [[ 5.78117184e-01 -3.28405147e-02  8.15292599e-01  1.65415479e+02]
 [-2.77054450e-01  9.31926440e-01  2.33995602e-01  9.58432594e+01]
 [-7.67477266e-01 -3.61157322e-01  5.29664078e-01  2.10488192e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000000

Translation:  [[-0.27763852]
 [-0.17711733]
 [ 0.48343104]]
C :  [[ 5.89585215e-01  2.61051836e-02  8.07284209e-01  1.71337007e+02]
 [-2.88741219e-01  9.40243751e-01  1.80472152e-01  9.74470004e+01]
 [-7.54332674e-01 -3.39499939e-01  5.61891457e-01  2.15740956e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 524
Translation:  [[0.12592315]
 [0.07523499]
 [0.5717909 ]]
C :  [[ 5.90141270e-01  2.77442662e-02  8.06823114e-01  1.71874811e+02]
 [-2.88566478e-01  9.40631422e-01  1.78723015e-01  9.75845728e+01]
 [-7.53964634e-01 -3.38293931e-01  5.63111487e-01  2.15941710e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 525
Translation:  [[ 0.22789509]
 [ 0.06966756]
 [-0.54639646]]
C :  [[ 5.90662814e-01  2.42104495e-02  8.06555202e-01  1.71570389e+02]
 [-2.83260024e-01  9.42160322e-01  1.79158274e-01  9.74866878e+01]
 [-7.55566807e-01 -3.34286976e-01  5.63356919e-01  2.15438635e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000

Translation:  [[-0.08353515]
 [ 0.00696479]
 [ 0.80813261]]
C :  [[ 6.41225809e-01  1.98205104e-02  7.67096219e-01  1.82539054e+02]
 [-1.82104424e-01  9.75039148e-01  1.27030066e-01  9.91069198e+01]
 [-7.45431043e-01 -2.21146572e-01  6.28829669e-01  2.21360702e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 548
Translation:  [[-0.15413979]
 [ 0.03840815]
 [ 0.80010072]]
C :  [[ 6.36555111e-01  1.34346814e-02  7.71114194e-01  1.83054731e+02]
 [-1.74192740e-01  9.76515736e-01  1.26782910e-01  9.92740756e+01]
 [-7.51301856e-01 -2.15026803e-01  6.23946307e-01  2.21970235e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 549
Translation:  [[-0.17940471]
 [ 0.04086249]
 [ 0.81020349]]
C :  [[ 6.32178399e-01  6.92806428e-03  7.74791891e-01  1.83565838e+02]
 [-1.66990160e-01  9.77678547e-01  1.27510566e-01  9.94479495e+01]
 [-7.56614009e-01 -2.09992047e-01  6.19224177e-01  2.22601759e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[-0.05706118]
 [-0.01603243]
 [ 0.91802518]]
C :  [[ 6.82625429e-01 -5.82988734e-02  7.28439267e-01  1.94629147e+02]
 [-9.66663414e-02  9.80849297e-01  1.69086590e-01  1.01303941e+02]
 [-7.24346700e-01 -1.85838365e-01  6.63917133e-01  2.33454387e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 572
Translation:  [[ 0.06683416]
 [-0.02113136]
 [ 0.91457218]]
C :  [[ 6.85848922e-01 -5.63766539e-02  7.25556979e-01  1.95342212e+02]
 [-9.75904364e-02  9.80864930e-01  1.68463927e-01  1.01431396e+02]
 [-7.21170828e-01 -1.86348225e-01  6.67223332e-01  2.34017103e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 573
Translation:  [[-0.00879942]
 [-0.02322158]
 [ 0.91119732]]
C :  [[ 6.84849040e-01 -6.19050430e-02  7.26050658e-01  1.95998612e+02]
 [-8.95497732e-02  9.81682256e-01  1.68168925e-01  1.01562981e+02]
 [-7.23161553e-01 -1.80187998e-01  6.66760567e-01  2.34635749e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[0.02667281]
 [0.01285293]
 [0.91738313]]
C :  [[ 6.71481214e-01 -5.87865546e-02  7.38686077e-01  2.04962677e+02]
 [-2.28511157e-01  9.31840366e-01  2.81879733e-01  1.05251944e+02]
 [-7.04908242e-01 -3.58074956e-01  6.12279916e-01  2.45371629e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 596
Translation:  [[ 0.08727172]
 [-0.02148678]
 [ 0.90931209]]
C :  [[ 6.78643017e-01 -6.28233095e-02  7.31776528e-01  2.05694238e+02]
 [-2.21135762e-01  9.32625832e-01  2.85145634e-01  1.05468296e+02]
 [-7.00387486e-01 -3.55334053e-01  6.19027528e-01  2.45874557e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 597
Translation:  [[ 0.11228561]
 [-0.01742543]
 [ 0.90586094]]
C :  [[ 6.86357858e-01 -6.00120827e-02  7.24783720e-01  2.06434422e+02]
 [-2.22349605e-01  9.31553993e-01  2.87693953e-01  1.05685516e+02]
 [-6.92440282e-01 -3.58616379e-01  6.26035741e-01  2.46362859e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000

Translation:  [[ 0.07634376]
 [-0.03014707]
 [ 0.88638212]]
C :  [[ 7.91318761e-01 -1.53436774e-01  5.91837625e-01  2.13479736e+02]
 [-8.26661002e-02  9.32258684e-01  3.52221609e-01  1.10208972e+02]
 [-6.05789513e-01 -3.27644476e-01  7.25029767e-01  2.56348805e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 620
Translation:  [[-0.60393076]
 [-0.06472179]
 [ 0.64271671]]
C :  [[ 7.90549319e-01 -1.38992048e-01  5.96416788e-01  2.13392149e+02]
 [-9.28205161e-02  9.35456122e-01  3.41036942e-01  1.10424937e+02]
 [-6.05323159e-01 -3.24966237e-01  7.26622886e-01  2.57201854e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 621
Translation:  [[8.87647896e-01]
 [6.78321353e-14]
 [2.36955724e-12]]
C :  [[ 7.90549319e-01 -1.38735595e-01  5.96476495e-01  2.14093878e+02]
 [-9.28205161e-02  9.35602670e-01  3.40634695e-01  1.10342546e+02]
 [-6.05323159e-01 -3.24653782e-01  7.26762544e-01  2.56664540e+02]
 [ 0.00000000e+00  0.00000000

Translation:  [[-0.06435443]
 [ 0.04638595]
 [ 0.88086564]]
C :  [[ 7.77041221e-01 -1.30517117e-01  6.15769619e-01  2.18590705e+02]
 [-1.12174261e-01  9.33893678e-01  3.39498944e-01  1.14307213e+02]
 [-6.19373778e-01 -3.32878176e-01  7.11033222e-01  2.66771128e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 644
Translation:  [[-0.49347654]
 [-0.14379789]
 [ 0.6915931 ]]
C :  [[ 7.76943893e-01 -1.02876306e-01  6.21107601e-01  2.18651884e+02]
 [-1.35366975e-01  9.36185875e-01  3.24394498e-01  1.14463072e+02]
 [-6.14844671e-01 -3.36113781e-01  7.13437844e-01  2.67616387e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 645
Translation:  [[-0.14822729]
 [ 0.03517677]
 [ 0.90797729]]
C :  [[ 7.77123004e-01 -1.09285348e-01  6.19787504e-01  2.19097052e+02]
 [-1.28482116e-01  9.36517748e-01  3.26231288e-01  1.14810612e+02]
 [-6.16094297e-01 -3.33153448e-01  7.13748273e-01  2.68343486e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[0.00113753]
 [0.00648286]
 [0.82636276]]
C :  [[ 7.28212654e-01  1.02121313e-01  6.77700205e-01  2.27405432e+02]
 [-3.62268507e-01  8.96757837e-01  2.54139548e-01  1.20462712e+02]
 [-5.81779906e-01 -4.30577076e-01  6.90025741e-01  2.82660812e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 668
Translation:  [[-0.03091497]
 [ 0.01812946]
 [ 0.81284284]]
C :  [[ 7.27993140e-01  1.01203887e-01  6.78073567e-01  2.27935634e+02]
 [-3.58527719e-01  8.99222769e-01  2.50711558e-01  1.20696744e+02]
 [-5.84366206e-01 -4.25624464e-01  6.90912406e-01  2.83231874e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 669
Translation:  [[ 0.41376553]
 [ 0.09381457]
 [-0.68308326]]
C :  [[ 7.28088170e-01  1.15193242e-01  6.75735254e-01  2.27783167e+02]
 [-3.65134518e-01  8.99462609e-01  2.40091231e-01  1.20461501e+02]
 [-5.80141707e-01 -4.21541851e-01  6.96949114e-01  2.82478203e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000

Translation:  [[ 0.05298212]
 [-0.03617256]
 [ 0.7093116 ]]
C :  [[ 6.20811291e-01 -2.85811203e-02  7.83438868e-01  2.37186422e+02]
 [-2.86780801e-01  9.21791207e-01  2.60878791e-01  1.25402651e+02]
 [-7.29623268e-01 -3.86631725e-01  5.64061872e-01  2.94642233e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 692
Translation:  [[ 0.07520197]
 [-0.0407054 ]
 [ 0.69782574]]
C :  [[ 6.24086138e-01 -3.35494036e-02  7.80634953e-01  2.37780976e+02]
 [-2.80402612e-01  9.22911522e-01  2.63834605e-01  1.25525611e+02]
 [-7.29308486e-01 -3.83547599e-01  5.66568947e-01  2.94996718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 693
Translation:  [[ 0.0482327 ]
 [-0.06260548]
 [ 0.69568859]]
C :  [[ 6.27678387e-01 -3.69858114e-02  7.77593655e-01  2.38356256e+02]
 [-2.78999729e-01  9.21828465e-01  2.69056560e-01  1.25637854e+02]
 [-7.26759241e-01 -3.85829407e-01  5.68292772e-01  2.95379710e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[-0.19565898]
 [-0.18535346]
 [ 0.36254938]]
C :  [[-7.36681320e-01 -8.86256670e-02 -6.70407431e-01  2.35742696e+02]
 [ 2.40279584e-01 -9.60988340e-01 -1.36993184e-01  1.24854839e+02]
 [-6.32112612e-01 -2.62005538e-01  7.29237097e-01  3.00788977e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 716
Translation:  [[ 0.12878448]
 [-0.012594  ]
 [ 0.42148568]]
C :  [[-7.38380630e-01 -9.03192203e-02 -6.68308673e-01  2.35366372e+02]
 [ 2.45441159e-01 -9.59018832e-01 -1.41568063e-01  1.24840145e+02]
 [-6.28134287e-01 -2.68561571e-01  7.30288984e-01  3.01018233e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 717
Translation:  [[ 0.29637792]
 [ 0.02705018]
 [-0.31523898]]
C :  [[-7.34982667e-01 -1.04410508e-01 -6.69999198e-01  2.35355766e+02]
 [ 2.57062591e-01 -9.57223301e-01 -1.32824603e-01  1.24931575e+02]
 [-6.27470560e-01 -2.69855511e-01  7.30382571e-01  3.00594588e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0

Translation:  [[ 0.17478011]
 [-0.02368563]
 [ 0.22298541]]
C :  [[-1.30443042e-01  3.34541188e-01  9.33309598e-01  2.34233408e+02]
 [ 2.16033266e-01  9.28324651e-01 -3.02560689e-01  1.24558415e+02]
 [-9.67633319e-01  1.62158984e-01 -1.93365517e-01  3.02758841e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 740
Translation:  [[0.08516627]
 [0.02268393]
 [0.28432668]]
C :  [[-1.09517111e-01  3.38660372e-01  9.34513325e-01  2.34495252e+02]
 [ 2.21220633e-01  9.24892771e-01 -3.09248758e-01  1.24511846e+02]
 [-9.69054918e-01  1.72865599e-01 -1.76210246e-01  3.02625131e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 741
Translation:  [[ 0.22847098]
 [-0.03507095]
 [ 0.18496886]]
C :  [[-1.02256052e-01  3.23752382e-01  9.40599859e-01  2.34631209e+02]
 [ 2.04878151e-01  9.32138760e-01 -2.98567037e-01  1.24472750e+02]
 [-9.73431376e-01  1.62178074e-01 -1.61646619e-01  3.02365074e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000

Translation:  [[0.15503011]
 [0.00309155]
 [0.23003068]]
C :  [[ 1.69038468e-01 -3.22044412e-01 -9.31511349e-01  2.33720914e+02]
 [ 2.78700583e-01 -8.90921784e-01  3.58586615e-01  1.24954311e+02]
 [-9.45384568e-01 -3.20227688e-01 -6.08460878e-02  3.01478826e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 764
Translation:  [[ 0.08606616]
 [-0.00290677]
 [ 0.27375988]]
C :  [[ 1.79105743e-01 -3.20420086e-01 -9.30189282e-01  2.33481389e+02]
 [ 2.74036899e-01 -8.91811983e-01  3.59965505e-01  1.25079054e+02]
 [-9.44894127e-01 -3.19378076e-01 -7.19217215e-02  3.01381734e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 765
Translation:  [[0.10341698]
 [0.00147951]
 [0.26802928]]
C :  [[ 1.88930626e-01 -3.20555882e-01 -9.28196717e-01  2.33250119e+02]
 [ 2.69556671e-01 -8.91981594e-01  3.62916019e-01  1.25202556e+02]
 [-9.44269252e-01 -3.18767568e-01 -8.21146645e-02  3.01264267e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000000

Translation:  [[-0.06212473]
 [-0.00232918]
 [-0.07177738]]
C :  [[-2.32969203e-02 -3.82474862e-01 -9.23672146e-01  2.31419008e+02]
 [ 3.00967784e-01 -8.83743980e-01  3.58350347e-01  1.25836774e+02]
 [-9.53349698e-01 -2.69647100e-01  1.35701125e-01  3.01151846e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 788
Translation:  [[ 0.08913463]
 [-0.00114448]
 [-0.00719264]]
C :  [[-2.55365219e-02 -4.01576011e-01 -9.15469603e-01  2.31424012e+02]
 [ 3.03611531e-01 -8.75626850e-01  3.75629681e-01  1.25862035e+02]
 [-9.52453634e-01 -2.68354852e-01  1.44283571e-01  3.01066202e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration 789
Translation:  [[0.03202941]
 [0.02790027]
 [0.07262472]]
C :  [[-6.75768786e-01 -2.20868975e-01 -7.03244939e-01  2.31345505e+02]
 [-1.96387467e-01  9.73516235e-01 -1.17038899e-01  1.25874609e+02]
 [ 7.10470626e-01  5.90172576e-02 -7.01247782e-01  3.01038687e+02]
 [ 0.00000000e+00  0.00000000e+00  0.0000